### ISSUE TITLE
scipy dependency?

### ISSUE THREAD

**Issue by haraldschilly** [conda-forge/pycaret-feedstock#22]
### Comment:

I'm mainly curious about the `scipy <=1.5.4` dependency. Is this really true? Upstream it says `<2`. It's just that there is certainly interest to have a newer version of scipy in the mix when using that package.

**Comment by kellend-git** [comment]
Hi @haraldschilly, we should match upstream - I will test a build with <2.

**Comment by kellend-git** [comment]
Fixed in #24
